version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: ~/kinase
    steps:
      - checkout
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.5
      - run: export PATH="$HOME/.yarn/bin:$PATH" && yarn && yarn test
