export const PORT_NAME = 'TENT';

export const ADD_COLLECTION_MAPPING = 'ADD_COLLECTION_MAPPING';
export const DELETE_COLLECTION_MAPPING = 'DELETE_COLLECTION_MAPPING';
export const SELECT_ELEMENT = 'SELECT_ELEMENT';
export const SET_CURRENT_FIELD = 'SET_CURRENT_FIELD';
export const UPDATE_FIELD = 'UPDATE_FIELD';
